# Generated by Django 4.1.7 on 2023-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('intensity', models.CharField(max_length=122)),
                ('sector', models.CharField(max_length=122)),
                ('topic', models.CharField(max_length=122)),
                ('insight', models.CharField(max_length=122)),
                ('url', models.URLField(blank=True)),
                ('region', models.CharField(max_length=122)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('impact', models.CharField(max_length=122)),
                ('country', models.CharField(max_length=122)),
                ('pestle', models.CharField(max_length=122)),
                ('source', models.CharField(max_length=122)),
                ('title', models.TextField()),
                ('likelihood', models.CharField(max_length=122)),
            ],
        ),
    ]
