# Generated by Django 4.1.7 on 2023-02-23 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 13, 37, 47, 165647, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
