# Generated by Django 4.1.7 on 2023-02-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_details_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='added',
        ),
        migrations.AddField(
            model_name='details',
            name='revelance',
            field=models.IntegerField(default=True),
        ),
    ]
