# Generated by Django 4.1.7 on 2023-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_details_added_details_revelance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='revelance',
            field=models.FloatField(),
        ),
    ]
